### ISSUE TITLE
Unexpected file names

### ISSUE THREAD

**Issue by edunfelt** [richardneililagan/base16-builder-node#9]
Hi,

I encountered a problem while trying to match theme names generated by the builder to the env variable `BASE16_THEME` set by base16-shell. As I understand it, base16-shell uses the [`scheme-slug`](https://github.com/base16-project/base16/blob/main/builder.md#template-variables=) to set the variable but this does not seem to be how the theme names are generated by this builder. For example, some themes, such as [Heetch](https://github.com/base16-project/base16-schemes/blob/main/heetch.yaml) does not build to `base16-heetch.extension` but to `base16-heetch-dark.extension` as seen [here](https://github.com/edunfelt/base16-pyradio/blob/main/themes/base16-heetch-dark.pyradio-theme).

Is this intentional? Here is the discussion we had in base16-pyradio where this came up, for reference: edunfelt/base16-pyradio#10([comment](https://github.com/edunfelt/base16-pyradio/issues/10#issuecomment-1176123406)).

In any case, special characters in the name of some schemes seem to be dropped in the name of the generated theme files such as [Rosé Pine](https://github.com/base16-project/base16-schemes/blob/main/rose-pine.yaml) which seems to simply build to [base16-ros-pine](https://github.com/edunfelt/base16-pyradio/blob/main/themes/base16-ros-pine.pyradio-theme).

**Comment by joshgoebel** [comment]
@edunfelt Thanks for bringing this to my attention.  I'm pretty sure that the correct name (on disk) should be `heetch-dark`, that is the actual given name of scheme.  I'm not sure why "light" and "dark" should be removed.  Lets see what Jamy says.

@JamyGolden Why does base16-shell cut off the light/dark?  

> special characters in the name of some schemes seem to be dropped in the name of the generated theme files such as Rosé Pine which seems to simply build to base16-ros-pine.

That's a bug.  Though it's not 100% clear to me how we should deal with non-ASCII characters... i'm tempted to downsample them to ASCII...

**Comment by edunfelt** [comment]
@joshgoebel I agree, keeping the "light"/"dark" is nice as it could allow for further extending projects. (Me and @s-n-g were also discussing generating different templates depending on whether the theme is light or dark, but not all themes make this distinction currently so it seems hard to implement.)

Above all, consistency of theme names between projects I think should be prioritized for better integration between the tools.



> That's a bug. Though it's not 100% clear to me how we should deal with non-ASCII characters... i'm tempted to downsample them to ASCII...

Seems reasonble imo. :)

**Comment by joshgoebel** [comment]
> were also discussing generating different templates depending on whether the theme is light or dark

This is only waiting for us to decide on a name for the key that we'd use to specify `light` and `dark`... it's been discussed, then we'd expose `isDark` and `isLight` to the template and they could programmaticly do with those as it chose...

Likely would need to be something we added to the builder or style specs.

**Comment by joshgoebel** [comment]
@edunfelt Out of curiosity what does your template want to do with that information?

**Comment by s-n-g** [comment]
> @edunfelt Out of curiosity what does your template want to do with that information?

Sorry to chip in, but maybe I could shed some light here...

So, `pyradio` has this **global transparency** setting, which works in combination with the **themes' transparency setting**.

Themes can declare that they look good when transparency is off, or on, or do not care (in which case, global transparency comes into play). BTW, for curses turning the transparency on means that no background color is visible.

Currently, the template declares that transparency should be off.

Starting from the assumption that a dark theme will probably look good either way, if we had the distinction between dark/light, dark themes could declare that they do not care about it (and use the global setting instead)

**Comment by JamyGolden** [comment]
It looks like builder-go uses the name of the scheme as the name of the generated theme file. We use base16-builder-go for basically all of the internal projects ([emacs](https://github.com/base16-project/base16-emacs/tree/main/build), [shell](https://github.com/base16-project/base16-shell/tree/main/scripts), [vim](https://github.com/base16-project/base16-vim/tree/main/colors), [tmux](https://github.com/base16-project/base16-tmux/tree/main/colors), [iterm2](https://github.com/base16-project/base16-iterm2/tree/main/itermcolors), [conemu](https://github.com/base16-project/base16-conemu/tree/main/themes), [fzf](https://github.com/base16-project/base16-fzf/tree/main/bash))

I don't know golang, but based on the above templates not generating filenames like builder-node:
1. I'm guessing `"-"` is the filename without extension. https://github.com/base16-project/base16-builder-go/blob/main/scheme.go#L18
2. This is where the filename is created. https://github.com/base16-project/base16-builder-go/blob/main/template.go#L73

But again, since I don't know go I'm not sure.

**Comment by joshgoebel** [comment]
This is probably something for @belak and I to sort out and add to the builder spec.  One of these ways should be canonical I think so that the output from one builder to another is guaranteed to match.

_I personally very much dislike relying on **any** meta-data coming from OUTSIDE the scheme YAML._  The canonical "source of truth" for everything about a scheme (including it's naming) should be the `scheme` key of the YAML.  If all the filenames were somehow lost, we should be able to build all schemes from just the YAML contents alone.

That's my 0.02. :-)

**Comment by s-n-g** [comment]
Regarding https://github.com/base16-project/base16-builder-node/issues/9#issuecomment-1177326478

Come to think of it, that would not be so hard to implement... provided that the criterion is there :wink:

It would be enough to add a `dark.mustache` in https://github.com/edunfelt/base16-pyradio/tree/main/templates

Then, when creating the themes, if the theme is marked as dark, use the `dark.mustache`, else use the `default.mustache`

That would be nice!

**Comment by joshgoebel** [comment]
That would require larger builder changes, but you can do the same thing with a SINGLE template based purely on metadata:

```mustache
{{#isDark}}
# dark config here
{{/isDark}}
{{#isLight}}
# light config here
{{/isLight}}
```

If mustache was slightly more powerful you could do it today - by sniffing at the colors.

> use the dark.mustache, else use the default.mustache

_But what would dark do differently than default is my REAL question?_

**Comment by s-n-g** [comment]
For pyradio, not much (here is what that means for the app: https://github.com/base16-project/base16-builder-node/issues/9#issuecomment-1177326478 )

```
# Theme Transparency
# Values are:
#   0: No transparency (default)
#   1: Theme is transparent
#   2: Obey config setting
{{#isDark}}
transparency        2
{{/isDark}}
{{#isLight}}
transparency        0
{{/isLight}}
```

But I suppose themes for other apps might benefit in other ways

This is from https://github.com/edunfelt/base16-pyradio/blob/main/templates/default.mustache

**Comment by s-n-g** [comment]
Hi everybody!

While "playing" with pyradio, trying to sync base16 theme applied from terminal to the app, I get this

```
╭─spiros@py ~  
╰─➤  base16_synth-midnight-light 
╭─spiros@py ~  
╰─➤  ls -la ~/.config/base16-project/base16_shell_theme 
lrwxrwxrwx 1 spiros spiros 72 Jul  8 08:57 /home/spiros/.config/base16-project/base16_shell_theme -> /home/spiros/.config/base16-shell/scripts/base16-synth-midnight-light.sh
╭─spiros@py ~  
╰─➤  echo $BASE16_THEME
synth-midnight-light
```

But...
```
╭─spiros@py ~/projects/base16-pyradio  ‹main*› 
╰─➤  git pull 
Already up to date.
╭─spiros@py ~/projects/base16-pyradio  ‹main*› 
╰─➤  git remote -v
origin	git@github.com:s-n-g/base16-pyradio.git (fetch)
origin	git@github.com:s-n-g/base16-pyradio.git (push)
upstream	https://github.com/edunfelt/base16-pyradio.git (fetch)
upstream	https://github.com/edunfelt/base16-pyradio.git (push)
╭─spiros@py ~/projects/base16-pyradio  ‹main*› 
╰─➤  ls themes/*synth-mid*
themes/base16-synth-midnight-terminal-dark.pyradio-theme
themes/base16-synth-midnight-terminal-light.pyradio-theme
```

So, it's not just the `-dark` part that's somehow added...
Now I have a `-terminal` part...
Are we all using the same builder / schemes / whatever?

**Comment by joshgoebel** [comment]
As mentioned already node builder uses the name from the metadata which I believe is correct. Go builder uses the filename as name.  I need to write up why I feel this is broken in an issue on the other repo so we can have a discussion and resolve the matter. 

If we ultimately decide the spec is correct then this is a bug I need to fix.

**Comment by s-n-g** [comment]
Do you mean this one here?
https://github.com/base16-project/base16-builder-go/blob/main/scheme.go#L77

```
ret.Slug = filepath.Base(strings.TrimSuffix(fileName, ".yaml"))
```

used in
https://github.com/base16-project/base16-builder-go/blob/main/template.go#L73

I hope I understand it correctly...



There is no character transformation here, no part added (`-dark` or `-terminal`)...

This is equivalent to bash:

```
$ filenNme="/whatever/my-file.yaml"
$ basename "$fileName"
my-file.yaml
$  f=$(basename "$fileName")
$ echo "$f"
my-file.yaml
$ echo "${f/.yaml/}"
my-file
```

The only way to get something different, is to start with a different **fileName**

**Comment by joshgoebel** [comment]
From the YAML:

```
scheme: "Synth Midnight Terminal Dark"
```

When using Node builder the build product will be based on that - the canonical name - not the filename. So the slug becomes:


`base16-synth-midnight-terminal-dark.pyradio-theme`

**Comment by s-n-g** [comment]
Oh, I get it...

You are referring to https://github.com/base16-project/base16-builder-node/blob/main/lib/scheme.class.js#L76
using https://github.com/base16-project/base16-builder-node/blob/9b8da48709f874dea32e3a2d18a8097e659d3c03/lib/util/slug.js

**Comment by belak** [comment]
This was a change made from a previous spec (0.8.1) because we didn't want to deal with defining unicode folding or making a specific slugify algorithm a part of the spec. Using the filename was not a mistake. 

The old repo is gone, but I dug up the old issues:
- https://web.archive.org/web/20210124190414/https://github.com/chriskempson/base16/issues/60 
- https://web.archive.org/web/20210124190407/https://github.com/chriskempson/base16/issues/78
- https://web.archive.org/web/20210124190045/https://github.com/chriskempson/base16/pull/107

**Comment by joshgoebel** [comment]
Version 1.2.0 resolves this issue.
